# Generated by Django 2.0.5 on 2018-07-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.IntegerField()),
                ('dev_name', models.CharField(max_length=100)),
                ('dev_score_Documentation', models.FloatField(default=0)),
                ('dev_score_CodeStyle', models.FloatField(default=0)),
                ('dev_score_Performance', models.FloatField(default=0)),
                ('dev_score_BestPractices', models.FloatField(default=0)),
                ('dev_score_Security', models.FloatField(default=0)),
                ('dev_score_Multithreading', models.FloatField(default=0)),
                ('dev_score_Design', models.FloatField(default=0)),
                ('dev_score_ErrorProne', models.FloatField(default=0)),
                ('dev_score_All', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.IntegerField()),
                ('proj_name', models.CharField(max_length=100)),
                ('proj_stars', models.IntegerField(default=0)),
            ],
        ),
    ]
