# Generated by Django 2.0.5 on 2018-06-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookingSociety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooker',
            name='skill1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cooker',
            name='skill2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cooker',
            name='skill3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cooker',
            name='skill4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cooker',
            name='skill5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cooker',
            name='skill6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='req1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='req2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='req3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='req4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='req5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='req6',
            field=models.IntegerField(default=0),
        ),
    ]
